project:
  version: @project.version@

server:
  port: 8080



spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.87.101.103:3306/nbiot?useUnicode=true&characterEncoding=utf8
    username: nbiot
    password: nbiot100202
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
          hibernate:
            dialect: com.croxx.nbiot.config.MySQL5InnoDBDialectUtf8mb4
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    org.springframework: INFO
    com.croxx.nbiot: INFO
  file: nbiot.log

jwt:
    header: Authorization
    secret: a6bcd6e36a024d847d3c915188f2ae6b5cc44e38
    expiration: 43200
    tokenHead: "Bearer "


#nbiot:
#  appId: cb8ea299-122c-40d2-a323-d4690a313da7
#  secret: 1843e98abdf843b86b69
#  platform:
#    host: 218.4.33.71
#    port: 8743

#nbiot:
#  appId: PcH6DS2vvO4_0ywnlaCF4Hfb01oa
#  secret: PB4lrxotkNR5F0NUdpEfsfcAnDsa
#  platform:
#    host: 117.78.47.187
#    port: 8743

# fuweinbiot
# Huawei12#$
# APP_ID:PcH6DS2vvO4_0ywnlaCF4Hfb01oa
# APP_PWD:PB4lrxotkNR5F0NUdpEfsfcAnDsa
# https://117.78.47.187:8093/

nbiot:
  appId: kAQt43oyTmKfOa2spyCVnRVuJBoa
  secret: m8ifHaDjJlfiJpWIiU2zA9q0rBQa
  platform:
    host: 218.4.33.72
    port: 8743

# 15811556300
# 8Yr-m?Q7
# 218.4.33.72:8743
#
# kAQt43oyTmKfOa2spyCVnRVuJBoa
# m8ifHaDjJlfiJpWIiU2zA9q0rBQa
# https://218.4.33.72:8093
# Sample Message Code:
#
# BaseInfo : 00030342E8EB85421FAE14
# 00 messageId
# 03 BatteryLevel
# 03 NetworkQuality
# 42E8EB85 LocationLongitude 116.46
# 421FAE14 LocationLatitude 39.92
#
# Click : 0140200000
# 01 messageId
# 40200000 ClickHoldtime 2.5

device:
  deviceType: OneButton
  model: OneTouch
  manufacturerId: Huawei
  manufacturerName: Huawei
  protocolType: CoAP
