project:
  version: @project.version@

server:
  port: 8080



spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.87.101.103:3306/nbiot
    username: nbiot
    password: nbiot100202
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

jwt:
    header: Authorization
    secret: a6bcd6e36a024d847d3c915188f2ae6b5cc44e38
    expiration: 43200
    tokenHead: "Bearer "


nbiot:
  appId: cb8ea299-122c-40d2-a323-d4690a313da7
  secret: 1843e98abdf843b86b69
  platform:
    host: 218.4.33.71
    port: 8743
